name: WakaTime Readme

on:
  schedule:
    # Jalan setiap jam 12 malam
    - cron: '0 0 * * *'
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  update-readme:
    name: Update Readme with WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/wakatime-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}